apiVersion: apps/v1
kind: Deployment

metadata:
  name: history-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: history

  template:
    metadata:
      labels:
        app: history

    spec:
      containers:
      - name: history-container
        image: jeswin07/history-service:v2
        imagePullPolicy: Always

        ports:
        - containerPort: 8003

        env:
        - name: DB_HOST
          value: "db"

---
apiVersion: v1
kind: Service
metadata:
  name: history-service
spec:
  selector:
    app: history
  ports:
    - port: 8003
      targetPort: 8003